### ISSUE TITLE
Application insights winston publisher issue with log level

### ISSUE THREAD

**Issue by vitalisks** [hectorhdzg/aplicationinsights-example#1]
Hi,

Sorry. It is not possible directly to reach you regarding the issue we've found in our projects, but seems you're quite active microsoft contributor, so would gladly to ask if you could help to fix issue reported in https://github.com/microsoft/node-diagnostic-channel/pull/116, where log level set on the winston configuration level is ignored and most verbose level is always used.

Regards,

Vitaliy.

**Comment by vitalisks** [comment]
Thank you!

Are there any plans to release patch 2.9.2 for application insights in the nearest future?

**Comment by hectorhdzg** [comment]
@vitalisks we are currently on release Freeze but we will do a release for all of our packages second week of January
